Repository hctnm1/Learn-To-Use-Github, pull requests merged in 2022-10, with the labels that each got.

#208 Data Wrangling Python - Data Science
  Projects/Data Wrangling Python/acces_data_coloum.py
  Projects/Data Wrangling Python/acces_data_coloums_line_certain.py
  Projects/Data Wrangling Python/acces_data_line.py
  Projects/Data Wrangling Python/check_null_value.py
  Projects/Data Wrangling Python/fill_with_mean.py
  Projects/Data Wrangling Python/fill_with_median.py
  Projects/Data Wrangling Python/information_stats_numpy.py
  Projects/Data Wrangling Python/normalize_with_scikitlearn.py
  Projects/Data Wrangling Python/read_file_head.py
  Projects/Data Wrangling Python/read_file_pandas.py
  Projects/Data Wrangling Python/view_data_range_certain.py
Labels: hacktoberfest-accepted, hacktoberfest

#209 Source code for simple TIC TAC TOE
  Projects/TIC_TAC_TOE.py
Labels: hacktoberfest-accepted, hacktoberfest

#211 Doing My Part.
  Projects/Joke_Generator.py
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#212 Doing My Part.
  Projects/Calculator.py
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#213 Create FlappyBird.py
  Projects/FlappyBird.py
Labels: hacktoberfest-accepted, hacktoberfest

#214 Create Text_to_speech.py
  Projects/Text_to_speech.py
Labels: hacktoberfest-accepted, hacktoberfest

#215 Patch 4
  Projects/Reverse-Array.js
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#216 #yagami
  Projects/towerofhanoi.c
Labels: hacktoberfest-accepted, hacktoberfest

#217 #light
  Projects/travelsalesman.c
Labels: hacktoberfest-accepted, hacktoberfest

#219 Patch 3
  Projects/BMICalc.py
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#218 Added Text Highlighter Project
  Projects/Text Highlighter/highlight.html
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#221 # real yagami 1
  Projects/iptracker.py
Labels: hacktoberfest-accepted

#220 checking prime number
  Projects/checkprime.py
Labels: hacktoberfest-accepted

#231 Create PigeonHole_Sort.py
  Projects/PigeonHole_Sort.py
Labels: hacktoberfest-accepted

#232 Create Floyd's Triangle.cpp
  Projects/Floyd's Triangle.cpp
Labels: merge when passing

#233 Create Fibonacci.java
  Projects/Fibonacci.java
Labels: good first issue, hacktoberfest-accepted

#234 Create InsertionSort.js
  Projects/InsertionSort.js
Labels: good first issue, hacktoberfest-accepted

#235 Create Pacman.py
  Projects/Pacman.py
Labels: good first issue, hacktoberfest-accepted

#236 #real yagami 2Create dijkstra.java
  Projects/dijkstra.java
Labels: hacktoberfest-accepted

#238 C++ program for fibonacci series
  Projects/fibo.cpp
Labels: good first issue, hacktoberfest-accepted

#237 #real yagami 3 Create pigenhole.py
  Projects/pigenhole.py
Labels: good first issue, hacktoberfest-accepted

#239 #real yagami 4 Create birthcalculator.py
  Projects/birthcalculator.py
Labels: hacktoberfest-accepted

#240 #real yagami 5 Create bucket_sort.java
  Projects/bucket_sort.java
Labels: good first issue, hacktoberfest-accepted

#241 real yagami 6 Create push_zero_to_end.py
  Projects/push_zero_to_end.py
Labels: good first issue, hacktoberfest-accepted

#245 Create bitwise_multiplication.cpp
  Projects/bitwise_multiplication.cpp
Labels: good first issue, hacktoberfest-accepted

#247 Create tributepage.hmtl
  Projects/tributepage.hmtl
Labels: good first issue, hacktoberfest-accepted

#249 Create json2csv.py
  Projects/json2csv.py
Labels: good first issue, hacktoberfest-accepted

#253 Reverse string in java
  Projects/reversestr.java
Labels: good first issue, hacktoberfest-accepted

#243 Create SNAKE_GAME_USING_JAVA.java
  Projects/DICE_GAME_LUDO.html
  Projects/SNAKE_GAME_USING_JAVA.java
  Two_Player_Luck_Game.py
Labels: good first issue, hacktoberfest-accepted

#254 Circular Linked List added
  Projects/Circular_LL.c
Labels: good first issue, hacktoberfest-accepted

#251 Create star-pattern.py
  Projects/star-pattern.py
Labels: good first issue, hacktoberfest-accepted

#246 Create dinicalgo.cpp
  Projects/dinicalgo.cpp
Labels: good first issue, hacktoberfest-accepted

#255 Create DoublyLinkedList_ADT.c
  Projects/DoublyLinkedList_ADT.c
Labels: good first issue, hacktoberfest-accepted

#250 Create romanDecimal.py
  Projects/romanDecimal.py
Labels: good first issue, hacktoberfest-accepted

#280 ci(Mergify): configuration update
  .mergify.yml
Labels: good first issue, hacktoberfest-accepted
